add_library(connecttool_protocol STATIC multiplex_protocol.cpp)
add_library(ConnectTool::Protocol ALIAS connecttool_protocol)
target_include_directories(connecttool_protocol PUBLIC ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(connecttool_protocol PUBLIC connecttool_domain)
target_compile_features(connecttool_protocol PUBLIC cxx_std_23)

connecttool_enable_strict_warnings(connecttool_protocol)
